import cv2
import numpy as np
import streamlit as st
from ultralytics import YOLO

# The stream-lit library is used to set up an interactive web-app!
# YOLOv8 model is used to detect fabric defects!

# Setting the page configuration!
st.set_page_config(page_title = "Fabric Defect Inspector", layout = "wide")

# App header!
st.title("Fabric Defect Inspector")
st.markdown("Upload a photo of your fabric. The algorithm will isolate statistical color anomalies (stains, wrong threads) and mark them out!")

# Caching to avoid long wait-times on the web-app!
@st.cache_resource
def loadModel():
    # Pointing to the exact file generated by train.py script!
    return YOLO("model/bestVersionOne.pt")
model = loadModel()

# File up-loader widget!
uploadedFile = st.file_uploader("Upload Fabric Image", type = ["png", "jpg", "jpeg"])

if uploadedFile is not None:
    # Stream-lit files are read as byte-streams, so we convert them into a numpy matrix!
    fileBytes = np.asarray(bytearray(uploadedFile.read()), dtype = np.uint8)
    userInput = cv2.imdecode(fileBytes, 1)

    # Converting B-G-R to R-G-B!
    fabric = cv2.cvtColor(userInput, cv2.COLOR_BGR2RGB)

    # Creating two columns for a side-by-side UI layout!
    columnOne, columnTwo = st.columns(2)

    with columnOne:
        st.subheader("Original Fabric")
        st.image(fabric, width = "stretch")
    
    # Web-UI!
    st.sidebar.header("AI Parameters")
    st.sidebar.markdown("Set how confident the AI must be to flag a defect.")
    confidence = st.sidebar.slider("Confidence Threshold", 0.0, 1.0, 0.25, 0.05)

    with st.spinner("AI is inspecting the fabric..."):
        # Running the YOLO interface!
        results = model.predict(source = fabric, conf = confidence)

        # Drawing the bounding boxes on-to the fabric!
        processedFabric = results[0].plot()
        processedFabric = cv2.cvtColor(processedFabric, cv2.COLOR_BGR2RGB)

    with columnTwo:
        st.subheader("Inspection Results")
        st.image(processedFabric, width = "stretch")